# Generated by Django 4.1.1 on 2022-10-20 09:16

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityID', models.AutoField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=125, verbose_name='City Name')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255, verbose_name='Company Name')),
                ('Address1', models.CharField(max_length=500, verbose_name='Address1')),
                ('Address2', models.CharField(max_length=500, verbose_name='Address2')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.city', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('ContractID', models.AutoField(primary_key=True, serialize=False)),
                ('ContractName', models.CharField(max_length=500, verbose_name='Contract Name')),
                ('Description', models.TextField()),
                ('StartDate', models.DateTimeField(verbose_name='Start Date')),
                ('EndDate', models.DateTimeField(verbose_name='End Date')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='ContractSLA',
            fields=[
                ('SLAID', models.AutoField(primary_key=True, serialize=False)),
                ('ContractSLA', models.CharField(max_length=500, verbose_name='Contract SLA')),
            ],
        ),
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('CSID', models.AutoField(primary_key=True, serialize=False)),
                ('ContractStatus', models.CharField(max_length=500, verbose_name='Contract Status')),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('CTID', models.AutoField(primary_key=True, serialize=False)),
                ('ContractType', models.CharField(max_length=500, verbose_name='Contract Type')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CountryID', models.AutoField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=125, verbose_name='Country Name')),
            ],
        ),
        migrations.CreateModel(
            name='FieldEngineer',
            fields=[
                ('FEID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeID', models.CharField(max_length=255, verbose_name='Employee ID')),
                ('FirstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=255, verbose_name='Last Name')),
                ('Email', models.CharField(max_length=255, verbose_name='Email')),
                ('Mobile', models.CharField(max_length=255, verbose_name='Mobile')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.city', verbose_name='City')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=500, verbose_name='Project Name')),
                ('Description', models.TextField()),
                ('StartDate', models.DateTimeField(verbose_name='Start Date')),
                ('EndDate', models.DateTimeField(verbose_name='End Date')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('PSID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectStatus', models.CharField(max_length=255, verbose_name='Project Status')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('PTID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectType', models.CharField(max_length=255, verbose_name='Project Type')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('TID', models.AutoField(primary_key=True, serialize=False)),
                ('TicketNo', models.CharField(max_length=255, verbose_name='Ticket No')),
                ('ParentTicketNo', models.CharField(max_length=255, verbose_name='Parent Ticket No')),
                ('TicketCreateDate', models.DateTimeField(verbose_name='Ticket Create Date')),
                ('TicketScheduleDate', models.DateTimeField(verbose_name='Ticket Schedule Date')),
                ('TicketCompletedDate', models.DateTimeField(verbose_name='Ticket Completed Date')),
                ('Subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('ScopeOfWork', models.TextField(verbose_name='Scope Of Work')),
                ('TravelStart', models.DateTimeField(verbose_name='Ticket Start Date')),
                ('ArrivalOnSite', models.DateTimeField(verbose_name='Arrival On Site')),
                ('RepairStart', models.DateTimeField(verbose_name='Repair Start')),
                ('RepairStop', models.DateTimeField(verbose_name='Repair Stop')),
                ('LeaveSite', models.DateTimeField(verbose_name='Leave Site')),
                ('TravelStop', models.DateTimeField(verbose_name='Travel Stop')),
                ('KmStart', models.DateTimeField(verbose_name='Km Start')),
                ('KmTillSite', models.DateTimeField(verbose_name='Km Till Site')),
                ('KmEnd', models.DateTimeField(verbose_name='Km End')),
                ('EndClient', models.CharField(max_length=255, verbose_name='End Client')),
                ('SiteAddress', models.CharField(max_length=500, verbose_name='Site Address')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.city', verbose_name='City')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.client', verbose_name='Client')),
                ('Contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.contract', verbose_name='Contract')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('TSID', models.AutoField(primary_key=True, serialize=False)),
                ('TicketStatus', models.CharField(max_length=255, verbose_name='Ticekt Status')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('TTID', models.AutoField(primary_key=True, serialize=False)),
                ('TicketType', models.CharField(max_length=255, verbose_name='Ticket Type')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'HOD'), (2, 'STAFF'), (3, 'STUDENT')], default=1, max_length=50)),
                ('profile_pic', models.ImageField(upload_to='media/profile_pic')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TicketSubType',
            fields=[
                ('TSTID', models.AutoField(primary_key=True, serialize=False)),
                ('TicketSubType', models.CharField(max_length=255, verbose_name='Ticket Sub Type')),
                ('TicketType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.tickettype', verbose_name='Ticket Type')),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('TSHID', models.AutoField(primary_key=True, serialize=False)),
                ('HistoryDate', models.DateTimeField(verbose_name='History Date')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticketstatus', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='TicketInternalNotes',
            fields=[
                ('TINID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(verbose_name='Date')),
                ('Notes', models.TextField(verbose_name='Notes')),
                ('FieldEngineer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.fieldengineer', verbose_name='Field Engineer')),
                ('TicketNo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticket', verbose_name='Ticket No')),
            ],
        ),
        migrations.CreateModel(
            name='TicketExternalNotes',
            fields=[
                ('TENID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(verbose_name='Date')),
                ('Notes', models.TextField(verbose_name='Notes')),
                ('FieldEngineer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.fieldengineer', verbose_name='Field Engineer')),
                ('TicketNo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticket', verbose_name='Ticket No')),
            ],
        ),
        migrations.CreateModel(
            name='TicketExpenses',
            fields=[
                ('TEID', models.AutoField(primary_key=True, serialize=False)),
                ('ExpenseDate', models.DateTimeField(verbose_name='Expense Date')),
                ('Currency', models.CharField(max_length=255, verbose_name='Currency')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=255, verbose_name='Amount')),
                ('ExpenseReason', models.TextField(verbose_name='Expense Reason')),
                ('FieldEngineer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.fieldengineer', verbose_name='Field Engineer')),
                ('TicketNo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticket', verbose_name='Ticket No')),
            ],
        ),
        migrations.CreateModel(
            name='TicketActionHistory',
            fields=[
                ('TAHID', models.AutoField(primary_key=True, serialize=False)),
                ('ActionTime', models.DateTimeField(verbose_name='Action Time')),
                ('Action', models.TextField(verbose_name='Action')),
                ('FieldEngineer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.fieldengineer', verbose_name='Field Engineer')),
                ('TicketNo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticket', verbose_name='Ticket No')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='CurrentTicketStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticketstatus', verbose_name='Current Ticket Status'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='FEAssigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.fieldengineer', verbose_name='FE Assigned'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketSubType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticketsubtype', verbose_name='Ticket Sub Type'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.tickettype', verbose_name='Ticket Type'),
        ),
        migrations.CreateModel(
            name='ProjectSubType',
            fields=[
                ('PSTID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectSubType', models.CharField(max_length=500, verbose_name='Project Sub Type')),
                ('ProjectType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.projecttype', verbose_name='Project Type')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectSubType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.projectsubtype', verbose_name='Project Sub Type'),
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.projecttype', verbose_name='Project Type'),
        ),
        migrations.CreateModel(
            name='EndClient',
            fields=[
                ('EndClientID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255, verbose_name='Company Name')),
                ('Address1', models.CharField(max_length=500, verbose_name='Address1')),
                ('Address2', models.CharField(max_length=500, verbose_name='Address2')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.city', verbose_name='City')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.country', verbose_name='Country')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NtekApp.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='ContractSubType',
            fields=[
                ('CSTID', models.AutoField(primary_key=True, serialize=False)),
                ('ContractSubType', models.CharField(max_length=500, verbose_name='Contract Sub Type')),
                ('ContratctType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.contracttype', verbose_name='Contract Sub Type')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='ContractSLA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.contractsla', verbose_name='Contract SLA'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ContractType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.contracttype', verbose_name='Contract Type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='EndClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.endclient', verbose_name='End Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NtekApp.country', verbose_name='Country Name'),
        ),
    ]
