# Generated by Django 4.1.1 on 2022-10-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ProjectSubType',
        ),
        migrations.AddField(
            model_name='project',
            name='EndClient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.endclient', verbose_name='End Client'),
            preserve_default=False,
        ),
    ]
