# Generated by Django 4.1.1 on 2022-10-27 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0004_contract_cstatus_contract_clientrefno'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ClientRefNo',
            field=models.CharField(default=1, max_length=255, verbose_name='Client Ref No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectStauts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.projectstatus', verbose_name='Project Status'),
            preserve_default=False,
        ),
    ]
