# Generated by Django 4.1.1 on 2022-10-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0005_project_clientrefno_project_projectstauts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='EndDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='StartDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
