# Generated by Django 4.1.1 on 2022-10-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0006_alter_contract_enddate_alter_contract_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Billable',
            field=models.CharField(choices=[('Yes', 'Ye'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='TicketNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ticket No'),
        ),
    ]
