# Generated by Django 4.1.1 on 2022-10-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0007_ticket_billable_alter_ticket_ticketno'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAble',
            fields=[
                ('BAID', models.AutoField(primary_key=True, serialize=False)),
                ('Billable', models.CharField(max_length=255, verbose_name='Bill Able')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Billable',
        ),
    ]
