# Generated by Django 4.1.1 on 2022-10-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0008_billable_remove_ticket_billable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ParentTicketNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NtekApp.ticket'),
        ),
    ]
