# Generated by Django 4.1.1 on 2022-10-31 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0010_remove_ticket_arrivalonsite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ParentTicketNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NtekApp.ticket'),
        ),
    ]
