# Generated by Django 4.1.1 on 2022-10-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0011_ticket_parentticketno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ParentTicketNo',
        ),
    ]
