# Generated by Django 4.1.1 on 2022-10-31 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0012_remove_ticket_parentticketno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='EndClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.endclient', verbose_name='End Client'),
        ),
    ]
