# Generated by Django 4.1.1 on 2022-11-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0013_alter_ticket_endclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='TicketCanceled',
            field=models.BooleanField(default=False, verbose_name='Ticket Cancel'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketClosed',
            field=models.BooleanField(default=False, verbose_name='Ticket Closed'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketOnHold',
            field=models.BooleanField(default=False, verbose_name='Ticket On Hold'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketOpen',
            field=models.BooleanField(default=True, verbose_name='Ticket Open'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketSchedule',
            field=models.BooleanField(default=False, verbose_name='Ticket Schedule'),
        ),
    ]
