# Generated by Django 4.1.1 on 2022-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0014_ticket_ticketcanceled_ticket_ticketclosed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='descp',
            field=models.CharField(default=1, max_length=255, verbose_name='Description Field'),
            preserve_default=False,
        ),
    ]
