# Generated by Django 4.1.1 on 2022-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0017_remove_ticket_ticketopen_remove_ticket_descp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='TicketCompletedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Completed Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='TicketScheduleDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Schedule Date'),
        ),
    ]
