# Generated by Django 4.1.1 on 2022-11-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0018_alter_ticket_ticketcompleteddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.contract', verbose_name='Contract'),
        ),
    ]
