# Generated by Django 4.1.1 on 2022-11-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0019_alter_ticket_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='CancelledTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Cancelled Time'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ClosedTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Closed Time'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='OnHoldTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='On Hold Time'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='OpenTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Open Time'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ScheduleTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ticket Schedule'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketCanceled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ticket Cancel'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketClosed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ticket Closed'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketOnHold',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ticket On Hold'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketOpen',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Ticket Open'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='TicketSchedule',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ticket Schedule'),
        ),
    ]
