# Generated by Django 4.1.1 on 2022-11-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0020_ticket_cancelledtime_ticket_closedtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='CancelledTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled Time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ClosedTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed Time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='OnHoldTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='On Hold Time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='OpenTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Open Time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ScheduleTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Schedule'),
        ),
    ]
