# Generated by Django 4.1.1 on 2022-11-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0021_alter_ticket_cancelledtime_alter_ticket_closedtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='TicketOpen',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ticket Open'),
        ),
    ]
