# Generated by Django 4.1.1 on 2022-11-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0023_alter_ticket_ticketcanceled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='CancelledTime',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ClosedTime',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='OnHoldTime',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='OpenTime',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ScheduleTime',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='TicketCanceled',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='TicketClosed',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='TicketOnHold',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='TicketOpen',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='TicketSchedule',
        ),
        migrations.AddField(
            model_name='tickeadminstatus',
            name='CancelledTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled Time'),
        ),
        migrations.AddField(
            model_name='tickeadminstatus',
            name='ClosedTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed Time'),
        ),
        migrations.AddField(
            model_name='tickeadminstatus',
            name='OnHoldTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='On Hold Time'),
        ),
        migrations.AddField(
            model_name='tickeadminstatus',
            name='OpenTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Open Time'),
        ),
        migrations.AddField(
            model_name='tickeadminstatus',
            name='ScheduleTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Schedule'),
        ),
        migrations.AlterField(
            model_name='tickeadminstatus',
            name='TicketCanceled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ticket Cancel'),
        ),
        migrations.AlterField(
            model_name='tickeadminstatus',
            name='TicketClosed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ticket Closed'),
        ),
        migrations.AlterField(
            model_name='tickeadminstatus',
            name='TicketOnHold',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ticket On Hold'),
        ),
        migrations.AlterField(
            model_name='tickeadminstatus',
            name='TicketOpen',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ticket Open'),
        ),
        migrations.AlterField(
            model_name='tickeadminstatus',
            name='TicketSchedule',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ticket Schedule'),
        ),
    ]
