# Generated by Django 4.1.1 on 2022-11-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0025_alter_ticketexpenses_ticketno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='Ticket',
        ),
    ]
