# Generated by Django 4.1.1 on 2022-11-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0028_alter_tickeadminstatus_cancelledtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='TicketOpen',
        ),
        migrations.AlterField(
            model_name='tickeadminstatus',
            name='CancelledTime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cancelled Time'),
        ),
        migrations.AlterField(
            model_name='tickeadminstatus',
            name='ClosedTime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Closed Time'),
        ),
        migrations.AlterField(
            model_name='tickeadminstatus',
            name='OnHoldTime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='On Hold Time'),
        ),
        migrations.AlterField(
            model_name='tickeadminstatus',
            name='OpenTime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open Time'),
        ),
        migrations.AlterField(
            model_name='tickeadminstatus',
            name='ScheduleTime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ticket Schedule'),
        ),
    ]
