# Generated by Django 4.1.1 on 2022-11-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0031_alter_tickeadminstatus_cancelledtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='CancelledTime',
        ),
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='ClosedTime',
        ),
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='OnHoldTime',
        ),
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='OpenTime',
        ),
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='ScheduleTime',
        ),
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='TicketCanceled',
        ),
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='TicketClosed',
        ),
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='TicketOnHold',
        ),
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='TicketOpen',
        ),
        migrations.RemoveField(
            model_name='tickeadminstatus',
            name='TicketSchedule',
        ),
        migrations.AddField(
            model_name='tickeadminstatus',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tickeadminstatus',
            name='StatusDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Status Date'),
        ),
        migrations.AddField(
            model_name='tickeadminstatus',
            name='Ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticket', verbose_name='Ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickeadminstatus',
            name='TicketStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticketstatus', verbose_name='Ticket Status'),
            preserve_default=False,
        ),
    ]
