# Generated by Django 4.1.1 on 2022-11-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0032_remove_tickeadminstatus_cancelledtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAgainstFE',
            fields=[
                ('TAFEID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(verbose_name='Description')),
                ('FEngineer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.fieldengineer', verbose_name='Field Engineer')),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticket', verbose_name='Ticket No')),
            ],
        ),
    ]
