# Generated by Django 4.1.1 on 2022-11-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0033_ticketagainstfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketagainstfe',
            name='Email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='ticketagainstfe',
            name='Mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='ticketagainstfe',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
