# Generated by Django 4.1.1 on 2022-11-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0035_festatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FEWork',
            fields=[
                ('FEWID', models.AutoField(primary_key=True, serialize=False)),
                ('WorkDate', models.DateTimeField(blank=True, null=True, verbose_name='Work Date')),
                ('Kilometer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kilometer')),
                ('FStatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.festatus', verbose_name='Field Engineer Status')),
            ],
        ),
    ]
