# Generated by Django 4.1.1 on 2022-11-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0037_fework_fengg_fework_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkActivity',
            fields=[
                ('WAID', models.AutoField(primary_key=True, serialize=False)),
                ('WorkDate', models.DateTimeField(blank=True, null=True, verbose_name='Work Date')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('FEngg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.fieldengineer', verbose_name='Field Engineer')),
                ('RemoteClient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.client', verbose_name='Remote Client')),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.ticket', verbose_name='Ticket No')),
            ],
        ),
    ]
