# Generated by Django 4.1.1 on 2022-11-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0038_workactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workactivity',
            name='WorkDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activity Date'),
        ),
    ]
