# Generated by Django 4.1.1 on 2022-11-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0040_rename_workdate_workactivity_activitydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NtekApp.project', verbose_name='Project'),
        ),
    ]
