# Generated by Django 4.1.1 on 2022-11-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NtekApp', '0041_alter_ticket_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('ExpenseID', models.AutoField(primary_key=True, serialize=False)),
                ('Expense', models.CharField(blank=True, max_length=255, null=True, verbose_name='Expense')),
            ],
        ),
    ]
